### ISSUE TITLE
Make a script that parses SConstruct to get the config options

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera-website#26]
The [`config-options.rst`](https://github.com/Cantera/cantera-website/blob/master/pages/compiling/config-options.rst) file contains the text of the configuration options from the main Cantera SConstruct file. To prevent it getting out of date, we should make a script that parses the SConstruct and writes the `config-options.rst` file. 

The [ast module](https://docs.python.org/3/library/ast.html) will be useful since SConstruct is just a Python file. See also https://greentreesnakes.readthedocs.io/en/latest/

In the end, this should be turned into a plugin that runs on every bulid of the website.

**Comment by speth** [comment]
I think this might be significantly easier than having to parse the AST. There is the closely-related `scons help` command for printing out all of the options, which uses the function `formatOption` in the `site_scons/buildutils.py` file. So I think this would just be a slightly different version of `formatOption`.

**Comment by ischoegl** [comment]
Since this was written, there appears to have been some cleanup done in `buildutils.py` (@bryanwweber??) ... implementing something that reflects configuration options based on this work would be relatively simple, but I believe some of the options are platform dependent (e.g. on linux, the option `msvc_version` is not reachable). Any ideas?

**Comment by ischoegl** [comment]
This is closed via Cantera/cantera#1137 and #160 also … 🎉
